name: eventsphere
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  animated_text_kit: ^4.2.2
  url_launcher: ^6.0.20
  http: ^1.1.0
  image_picker: ^1.0.8
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/user.png
